export const ALL_BRANCH_REQUEST = "ALL_BRANCH_REQUEST";
export const ALL_BRANCH_SUCCESS = "ALL_BRANCH_SUCCESS";
export const ALL_BRANCH_FAIL = "ALL_BRANCH_FAIL";

export const NEW_BRANCH_REQUEST = "NEW_BRANCH_REQUEST";
export const NEW_BRANCH_SUCCESS = "NEW_BRANCH_SUCCESS";
export const NEW_BRANCH_RESET = "NEW_BRANCH_RESET";
export const NEW_BRANCH_FAIL = "NEW_BRANCH_FAIL";

export const UPDATE_BRANCH_REQUEST = "UPDATE_BRANCH_REQUEST";
export const UPDATE_BRANCH_SUCCESS = "UPDATE_BRANCH_SUCCESS";
export const UPDATE_BRANCH_RESET = "UPDATE_BRANCH_RESET";
export const UPDATE_BRANCH_FAIL = "UPDATE_BRANCH_FAIL";

export const DELETE_BRANCH_REQUEST = "DELETE_BRANCH_REQUEST";
export const DELETE_BRANCH_SUCCESS = "DELETE_BRANCH_SUCCESS";
export const DELETE_BRANCH_RESET = "DELETE_BRANCH_RESET";
export const DELETE_BRANCH_FAIL = "DELETE_BRANCH_FAIL";

export const BRANCH_DETAILS_REQUEST = "BRANCH_DETAILS_REQUEST";
export const BRANCH_DETAILS_SUCCESS = "BRANCH_DETAILS_SUCCESS";
export const BRANCH_DETAILS_FAIL = "BRANCH_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";