export const ALL_CONFIG_REQUEST = "ALL_CONFIG_REQUEST";
export const ALL_CONFIG_SUCCESS = "ALL_CONFIG_SUCCESS";
export const ALL_CONFIG_FAIL = "ALL_CONFIG_FAIL";

export const NEW_CONFIG_REQUEST = "NEW_CONFIG_REQUEST";
export const NEW_CONFIG_SUCCESS = "NEW_CONFIG_SUCCESS";
export const NEW_CONFIG_RESET = "NEW_CONFIG_RESET";
export const NEW_CONFIG_FAIL = "NEW_CONFIG_FAIL";

export const UPDATE_CONFIG_REQUEST = "UPDATE_CONFIG_REQUEST";
export const UPDATE_CONFIG_SUCCESS = "UPDATE_CONFIG_SUCCESS";
export const UPDATE_CONFIG_RESET = "UPDATE_CONFIG_RESET";
export const UPDATE_CONFIG_FAIL = "UPDATE_CONFIG_FAIL";

export const DELETE_CONFIG_REQUEST = "DELETE_CONFIG_REQUEST";
export const DELETE_CONFIG_SUCCESS = "DELETE_CONFIG_SUCCESS";
export const DELETE_CONFIG_RESET = "DELETE_CONFIG_RESET";
export const DELETE_CONFIG_FAIL = "DELETE_CONFIG_FAIL";

export const CONFIG_DETAILS_REQUEST = "CONFIG_DETAILS_REQUEST";
export const CONFIG_DETAILS_SUCCESS = "CONFIG_DETAILS_SUCCESS";
export const CONFIG_DETAILS_FAIL = "CONFIG_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";