export const ALL_COUNCIL_REQUEST = "ALL_COUNCIL_REQUEST";
export const ALL_COUNCIL_SUCCESS = "ALL_COUNCIL_SUCCESS";
export const ALL_COUNCIL_FAIL = "ALL_COUNCIL_FAIL";

export const NEW_COUNCIL_REQUEST = "NEW_COUNCIL_REQUEST";
export const NEW_COUNCIL_SUCCESS = "NEW_COUNCIL_SUCCESS";
export const NEW_COUNCIL_RESET = "NEW_COUNCIL_RESET";
export const NEW_COUNCIL_FAIL = "NEW_COUNCIL_FAIL";

export const UPDATE_COUNCIL_REQUEST = "UPDATE_COUNCIL_REQUEST";
export const UPDATE_COUNCIL_SUCCESS = "UPDATE_COUNCIL_SUCCESS";
export const UPDATE_COUNCIL_RESET = "UPDATE_COUNCIL_RESET";
export const UPDATE_COUNCIL_FAIL = "UPDATE_COUNCIL_FAIL";

export const DELETE_COUNCIL_REQUEST = "DELETE_COUNCIL_REQUEST";
export const DELETE_COUNCIL_SUCCESS = "DELETE_COUNCIL_SUCCESS";
export const DELETE_COUNCIL_RESET = "DELETE_COUNCIL_RESET";
export const DELETE_COUNCIL_FAIL = "DELETE_COUNCIL_FAIL";

export const COUNCIL_DETAILS_REQUEST = "COUNCIL_DETAILS_REQUEST";
export const COUNCIL_DETAILS_SUCCESS = "COUNCIL_DETAILS_SUCCESS";
export const COUNCIL_DETAILS_FAIL = "COUNCIL_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";