export const ALL_DEPARTMENT_REQUEST = "ALL_DEPARTMENT_REQUEST";
export const ALL_DEPARTMENT_SUCCESS = "ALL_DEPARTMENT_SUCCESS";
export const ALL_DEPARTMENT_FAIL = "ALL_DEPARTMENT_FAIL";

export const NEW_DEPARTMENT_REQUEST = "NEW_DEPARTMENT_REQUEST";
export const NEW_DEPARTMENT_SUCCESS = "NEW_DEPARTMENT_SUCCESS";
export const NEW_DEPARTMENT_RESET = "NEW_DEPARTMENT_RESET";
export const NEW_DEPARTMENT_FAIL = "NEW_DEPARTMENT_FAIL";

export const UPDATE_DEPARTMENT_REQUEST = "UPDATE_DEPARTMENT_REQUEST";
export const UPDATE_DEPARTMENT_SUCCESS = "UPDATE_DEPARTMENT_SUCCESS";
export const UPDATE_DEPARTMENT_RESET = "UPDATE_DEPARTMENT_RESET";
export const UPDATE_DEPARTMENT_FAIL = "UPDATE_DEPARTMENT_FAIL";

export const DELETE_DEPARTMENT_REQUEST = "DELETE_DEPARTMENT_REQUEST";
export const DELETE_DEPARTMENT_SUCCESS = "DELETE_DEPARTMENT_SUCCESS";
export const DELETE_DEPARTMENT_RESET = "DELETE_DEPARTMENT_RESET";
export const DELETE_DEPARTMENT_FAIL = "DELETE_DEPARTMENT_FAIL";

export const DEPARTMENT_DETAILS_REQUEST = "DEPARTMENT_DETAILS_REQUEST";
export const DEPARTMENT_DETAILS_SUCCESS = "DEPARTMENT_DETAILS_SUCCESS";
export const DEPARTMENT_DETAILS_FAIL = "DEPARTMENT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";