export const ALL_FAQ_REQUEST = "ALL_FAQ_REQUEST";
export const ALL_FAQ_SUCCESS = "ALL_FAQ_SUCCESS";
export const ALL_FAQ_FAIL = "ALL_FAQ_FAIL";

export const NEW_FAQ_REQUEST = "NEW_FAQ_REQUEST";
export const NEW_FAQ_SUCCESS = "NEW_FAQ_SUCCESS";
export const NEW_FAQ_RESET = "NEW_FAQ_RESET";
export const NEW_FAQ_FAIL = "NEW_FAQ_FAIL";

export const UPDATE_FAQ_REQUEST = "UPDATE_FAQ_REQUEST";
export const UPDATE_FAQ_SUCCESS = "UPDATE_FAQ_SUCCESS";
export const UPDATE_FAQ_RESET = "UPDATE_FAQ_RESET";
export const UPDATE_FAQ_FAIL = "UPDATE_FAQ_FAIL";

export const DELETE_FAQ_REQUEST = "DELETE_FAQ_REQUEST";
export const DELETE_FAQ_SUCCESS = "DELETE_FAQ_SUCCESS";
export const DELETE_FAQ_RESET = "DELETE_FAQ_RESET";
export const DELETE_FAQ_FAIL = "DELETE_FAQ_FAIL";

export const FAQ_DETAILS_REQUEST = "FAQ_DETAILS_REQUEST";
export const FAQ_DETAILS_SUCCESS = "FAQ_DETAILS_SUCCESS";
export const FAQ_DETAILS_FAIL = "FAQ_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";