export const ALL_NOTIFY_REQUEST = "ALL_NOTIFY_REQUEST";
export const ALL_NOTIFY_SUCCESS = "ALL_NOTIFY_SUCCESS";
export const ALL_NOTIFY_FAIL = "ALL_NOTIFY_FAIL";

export const NEW_NOTIFY_REQUEST = "NEW_NOTIFY_REQUEST";
export const NEW_NOTIFY_SUCCESS = "NEW_NOTIFY_SUCCESS";
export const NEW_NOTIFY_RESET = "NEW_NOTIFY_RESET";
export const NEW_NOTIFY_FAIL = "NEW_NOTIFY_FAIL";

export const UPDATE_NOTIFY_REQUEST = "UPDATE_NOTIFY_REQUEST";
export const UPDATE_NOTIFY_SUCCESS = "UPDATE_NOTIFY_SUCCESS";
export const UPDATE_NOTIFY_RESET = "UPDATE_NOTIFY_RESET";
export const UPDATE_NOTIFY_FAIL = "UPDATE_NOTIFY_FAIL";

export const DELETE_NOTIFY_REQUEST = "DELETE_NOTIFY_REQUEST";
export const DELETE_NOTIFY_SUCCESS = "DELETE_NOTIFY_SUCCESS";
export const DELETE_NOTIFY_RESET = "DELETE_NOTIFY_RESET";
export const DELETE_NOTIFY_FAIL = "DELETE_NOTIFY_FAIL";

export const NOTIFY_DETAILS_REQUEST = "NOTIFY_DETAILS_REQUEST";
export const NOTIFY_DETAILS_SUCCESS = "NOTIFY_DETAILS_SUCCESS";
export const NOTIFY_DETAILS_FAIL = "NOTIFY_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";