export const ALL_SCHOOLYEAR_REQUEST = "ALL_SCHOOLYEAR_REQUEST";
export const ALL_SCHOOLYEAR_SUCCESS = "ALL_SCHOOLYEAR_SUCCESS";
export const ALL_SCHOOLYEAR_FAIL = "ALL_SCHOOLYEAR_FAIL";

export const NEW_SCHOOLYEAR_REQUEST = "NEW_SCHOOLYEAR_REQUEST";
export const NEW_SCHOOLYEAR_SUCCESS = "NEW_SCHOOLYEAR_SUCCESS";
export const NEW_SCHOOLYEAR_RESET = "NEW_SCHOOLYEAR_RESET";
export const NEW_SCHOOLYEAR_FAIL = "NEW_SCHOOLYEAR_FAIL";

export const UPDATE_SCHOOLYEAR_REQUEST = "UPDATE_SCHOOLYEAR_REQUEST";
export const UPDATE_SCHOOLYEAR_SUCCESS = "UPDATE_SCHOOLYEAR_SUCCESS";
export const UPDATE_SCHOOLYEAR_RESET = "UPDATE_SCHOOLYEAR_RESET";
export const UPDATE_SCHOOLYEAR_FAIL = "UPDATE_SCHOOLYEAR_FAIL";

export const DELETE_SCHOOLYEAR_REQUEST = "DELETE_SCHOOLYEAR_REQUEST";
export const DELETE_SCHOOLYEAR_SUCCESS = "DELETE_SCHOOLYEAR_SUCCESS";
export const DELETE_SCHOOLYEAR_RESET = "DELETE_SCHOOLYEAR_RESET";
export const DELETE_SCHOOLYEAR_FAIL = "DELETE_SCHOOLYEAR_FAIL";

export const SCHOOLYEAR_DETAILS_REQUEST = "SCHOOLYEAR_DETAILS_REQUEST";
export const SCHOOLYEAR_DETAILS_SUCCESS = "SCHOOLYEAR_DETAILS_SUCCESS";
export const SCHOOLYEAR_DETAILS_FAIL = "SCHOOLYEAR_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";