export const ALL_SPECIALIZED_REQUEST = "ALL_SPECIALIZED_REQUEST";
export const ALL_SPECIALIZED_SUCCESS = "ALL_SPECIALIZED_SUCCESS";
export const ALL_SPECIALIZED_FAIL = "ALL_SPECIALIZED_FAIL";

export const NEW_SPECIALIZED_REQUEST = "NEW_SPECIALIZED_REQUEST";
export const NEW_SPECIALIZED_SUCCESS = "NEW_SPECIALIZED_SUCCESS";
export const NEW_SPECIALIZED_RESET = "NEW_SPECIALIZED_RESET";
export const NEW_SPECIALIZED_FAIL = "NEW_SPECIALIZED_FAIL";

export const UPDATE_SPECIALIZED_REQUEST = "UPDATE_SPECIALIZED_REQUEST";
export const UPDATE_SPECIALIZED_SUCCESS = "UPDATE_SPECIALIZED_SUCCESS";
export const UPDATE_SPECIALIZED_RESET = "UPDATE_SPECIALIZED_RESET";
export const UPDATE_SPECIALIZED_FAIL = "UPDATE_SPECIALIZED_FAIL";

export const DELETE_SPECIALIZED_REQUEST = "DELETE_SPECIALIZED_REQUEST";
export const DELETE_SPECIALIZED_SUCCESS = "DELETE_SPECIALIZED_SUCCESS";
export const DELETE_SPECIALIZED_RESET = "DELETE_SPECIALIZED_RESET";
export const DELETE_SPECIALIZED_FAIL = "DELETE_SPECIALIZED_FAIL";

export const SPECIALIZED_DETAILS_REQUEST = "SPECIALIZED_DETAILS_REQUEST";
export const SPECIALIZED_DETAILS_SUCCESS = "SPECIALIZED_DETAILS_SUCCESS";
export const SPECIALIZED_DETAILS_FAIL = "SPECIALIZED_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";