export const ALL_SUPPORT_REQUEST = "ALL_SUPPORT_REQUEST";
export const ALL_SUPPORT_SUCCESS = "ALL_SUPPORT_SUCCESS";
export const ALL_SUPPORT_FAIL = "ALL_SUPPORT_FAIL";

export const NEW_SUPPORT_REQUEST = "NEW_SUPPORT_REQUEST";
export const NEW_SUPPORT_SUCCESS = "NEW_SUPPORT_SUCCESS";
export const NEW_SUPPORT_RESET = "NEW_SUPPORT_RESET";
export const NEW_SUPPORT_FAIL = "NEW_SUPPORT_FAIL";

export const UPDATE_SUPPORT_REQUEST = "UPDATE_SUPPORT_REQUEST";
export const UPDATE_SUPPORT_SUCCESS = "UPDATE_SUPPORT_SUCCESS";
export const UPDATE_SUPPORT_RESET = "UPDATE_SUPPORT_RESET";
export const UPDATE_SUPPORT_FAIL = "UPDATE_SUPPORT_FAIL";

export const DELETE_SUPPORT_REQUEST = "DELETE_SUPPORT_REQUEST";
export const DELETE_SUPPORT_SUCCESS = "DELETE_SUPPORT_SUCCESS";
export const DELETE_SUPPORT_RESET = "DELETE_SUPPORT_RESET";
export const DELETE_SUPPORT_FAIL = "DELETE_SUPPORT_FAIL";

export const SUPPORT_DETAILS_REQUEST = "SUPPORT_DETAILS_REQUEST";
export const SUPPORT_DETAILS_SUCCESS = "SUPPORT_DETAILS_SUCCESS";
export const SUPPORT_DETAILS_FAIL = "SUPPORT_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";