export const ALL_TRAININGSYSTEM_REQUEST = "ALL_TRAININGSYSTEM_REQUEST";
export const ALL_TRAININGSYSTEM_SUCCESS = "ALL_TRAININGSYSTEM_SUCCESS";
export const ALL_TRAININGSYSTEM_FAIL = "ALL_TRAININGSYSTEM_FAIL";

export const NEW_TRAININGSYSTEM_REQUEST = "NEW_TRAININGSYSTEM_REQUEST";
export const NEW_TRAININGSYSTEM_SUCCESS = "NEW_TRAININGSYSTEM_SUCCESS";
export const NEW_TRAININGSYSTEM_RESET = "NEW_TRAININGSYSTEM_RESET";
export const NEW_TRAININGSYSTEM_FAIL = "NEW_TRAININGSYSTEM_FAIL";

export const UPDATE_TRAININGSYSTEM_REQUEST = "UPDATE_TRAININGSYSTEM_REQUEST";
export const UPDATE_TRAININGSYSTEM_SUCCESS = "UPDATE_TRAININGSYSTEM_SUCCESS";
export const UPDATE_TRAININGSYSTEM_RESET = "UPDATE_TRAININGSYSTEM_RESET";
export const UPDATE_TRAININGSYSTEM_FAIL = "UPDATE_TRAININGSYSTEM_FAIL";

export const DELETE_TRAININGSYSTEM_REQUEST = "DELETE_TRAININGSYSTEM_REQUEST";
export const DELETE_TRAININGSYSTEM_SUCCESS = "DELETE_TRAININGSYSTEM_SUCCESS";
export const DELETE_TRAININGSYSTEM_RESET = "DELETE_TRAININGSYSTEM_RESET";
export const DELETE_TRAININGSYSTEM_FAIL = "DELETE_TRAININGSYSTEM_FAIL";

export const TRAININGSYSTEM_DETAILS_REQUEST = "TRAININGSYSTEM_DETAILS_REQUEST";
export const TRAININGSYSTEM_DETAILS_SUCCESS = "TRAININGSYSTEM_DETAILS_SUCCESS";
export const TRAININGSYSTEM_DETAILS_FAIL = "TRAININGSYSTEM_DETAILS_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";